language: cpp

os: linux

dist: jammy

addons:
  apt:
    packages:
      - cmake
      - make

compiler:
  - gcc

before_script:
  - mkdir build
  - cd build
  - cmake ..

script:
  - make -j$(nproc)
  - make test
